### ISSUE TITLE
Update readme to clearly indicate what the module does

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-documentconverter#10]
Readme.md is **inconceivably** announcing that it creates a [_versionfeed_](https://github.com/silverstripe/silverstripe-versionfeed)

We should update to ensure that it correctly indicates what the module does.

**Comment by andrewandante** [comment]
![image](https://user-images.githubusercontent.com/9702648/38355767-c96fc808-38b5-11e8-9579-0d81a139efea.png)

**Comment by NightJar** [comment]
> I don't think this module does, what you think it does.

![image](https://user-images.githubusercontent.com/778003/38392894-2f70c4e6-397d-11e8-9116-07f76446a5b1.png)
