### ISSUE TITLE
UX Warning message needs bootstrap classes

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-documentconverter#12]
The below warning message in the CMS is not easily distinguishable from the other text and perhaps needs some styling:

 ![image](https://user-images.githubusercontent.com/14869519/38393524-299d6a0e-397f-11e8-9991-ec40d1fb6689.png)

**Comment by robbieaverill** [comment]
This should be an easy win! We probably just need to add the Bootstrap `alert alert-warning` classes to the message. Fancy a PR?
